# Generated by Django 5.0.6 on 2024-07-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('service_provider', '0003_remove_serviceproviderdetails_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerdetails')),
                ('service_provider_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.serviceproviderdetails')),
            ],
        ),
    ]
