# Generated by Django 5.0.6 on 2024-07-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
