# Generated by Django 5.0.6 on 2024-07-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
